/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public\\duck.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    character_duck: THREE.Mesh
    Cube1338: THREE.Mesh
    Cube1338_1: THREE.Mesh
  }
  materials: {
    ['White.026']: THREE.MeshStandardMaterial
    ['Yellow.043']: THREE.MeshStandardMaterial
    ['Black.027']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/duck-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_duck.geometry} material={materials['White.026']} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, 0.704, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube1338.geometry} material={materials['Yellow.043']} />
        <mesh geometry={nodes.Cube1338_1.geometry} material={materials['Black.027']} />
      </group>
    </group>
  )
}

useGLTF.preload('/duck-transformed.glb')
